# Generated by Django 4.2.10 on 2024-04-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(default='default_video.jpg', upload_to='videos_preview'),
        ),
    ]
