# Generated by Django 4.2.10 on 2024-04-16 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_date_registred_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_registred',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
