# Generated by Django 4.2.10 on 2024-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_date_registred_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_registred',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
