# Generated by Django 4.2.10 on 2024-04-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_registred',
            new_name='birthday',
        ),
    ]
