# Generated by Django 4.2.10 on 2024-04-19 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_date_registred_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
