# Generated by Django 4.2.10 on 2024-04-25 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('tag', models.CharField(default='', max_length=100)),
                ('preview', models.ImageField(default='default_article.jpg', upload_to='articles_preview')),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
