# Generated by Django 4.2.10 on 2024-05-04 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_author_alter_article_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
